通知功能
babalae/better-genshin-impact pull request #333
Opened 2024-03-27 23:09 UTC by Mr-Quin

draft防merge
试着做了以下我在 #251 提到的通知功能。主要是一些任务耗时较长，通知功能可以优化远程/后台使用的体验，不用隔一段时间手动检查了。
架构上应该可以支持添加更多的通知类型
目前只能算是个概念，还要对接各种任务模块
接触c#以来做的最复杂的东西了，诸位大哥可以帮忙瞅瞅

![image](https://github.com/babalae/better-genshin-impact/assets/8700123/33e51cdb-32ce-4000-a824-4474c8ec7dca)

2024-03-28 04:34 UTC, huiyadanli commented
先切换成review状态，不合并

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/b0f6ef61-af28-4cc7-9e34-3bdcaaf41ed1)

简单看了下（晚上再细看

1. `INotifier` 希望暴露出原始的通知方法，并和 BetterGI 的任务通知解耦。也许这个包以后可以作为独立的包使用（上传nuget
2. 希望通知模块支持图片的入参，可以暂时不实现

2024-03-28 05:30 UTC, Lightczx requested changes

2024-03-28 05:30 UTC, Lightczx commented on BetterGenshinImpact/Service/Notification/Notification.cs
> +namespace BetterGenshinImpact.Service.Notification
namespace style

2024-03-28 05:30 UTC, Lightczx commented on BetterGenshinImpact/Service/Notification/Notification.cs
> +    public interface INotifier
每个接口/类需要使用单独的文件

2024-03-28 05:30 UTC, Lightczx commented on BetterGenshinImpact/Service/Notification/Notification.cs
> +        Task<NotificationResponse> Notify(LifecycleNotificationData notificationData);
两个都要改成 NotifyAsync，并且我认为可以抽象出 INotificationData

2024-03-28 05:30 UTC, Lightczx commented on BetterGenshinImpact/Service/Notification/Notification.cs
> +            _httpClient = new HttpClient();
HttpClient 请直接注入，直接 new 的 HttpClient 非常不好

2024-03-28 05:30 UTC, Lightczx commented on BetterGenshinImpact/Service/Notification/Notification.cs
> +        private async Task<NotificationResponse> SendNotification(StringContent content)
SendNotificationAsync

2024-03-28 05:30 UTC, Lightczx commented on BetterGenshinImpact/Service/Notification/Notification.cs
> +            var serializedData = JsonConvert.SerializeObject(notificationData);
包括下面的Model定义，换成使用 System.Text.Json
另外所有的Model class 需要单独文件

2024-03-28 05:30 UTC, Lightczx commented on BetterGenshinImpact/Service/Notification/Notification.cs
> +        private async Task<NotificationResponse> SendNotification(StringContent content)
StringContent -> HttpContent

2024-03-28 05:30 UTC, Lightczx commented on BetterGenshinImpact/Service/Notification/Notification.cs
> +        public void NotifyObservers(TaskNotificationData d)
可以考虑NotifyAllObservers，单单使用复数结尾有时不够明显

2024-03-28 05:30 UTC, Lightczx commented on BetterGenshinImpact/Service/Notification/Notification.cs
> +            RegisterNotifier(new WebhookNotifier
这一步骤不应由NotificationManager实现，可以考虑继续在上层抽象一层，由上层完成注册

2024-03-28 05:30 UTC, Lightczx commented on BetterGenshinImpact/Service/Notification/Notification.cs
> +            RegisterNotifier(new WebhookNotifier
也可以考虑注册 AddSingleton/Transit/Scoped<INotifier, WebhookNotifier>
注入时使用  IEnumerable<INotifier> 获取
也可以考虑注册 AddKeyedSingleton/Transit/Scoped<INotifier, WebhookNotifier>(key)
注入时使用  INotifier, key 获取

2024-03-29 06:27 UTC, Mr-Quin commented
谢谢大哥的建议，refactor了一下
INotificationData这块还得琢磨琢磨,先添加了Image property

2024-03-29 07:01 UTC, Lightczx commented
> INotificationData和通知模板这块还得琢磨琢磨,先添加了Image property

![image](https://github.com/babalae/better-genshin-impact/assets/36357191/971286a3-32f5-408c-a83a-892c4fa07a2e)

2024-03-29 08:32 UTC, huiyadanli requested changes

2024-03-29 08:32 UTC, huiyadanli commented on BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
> +    private void Notify(NotificationAction action, NotificationConclusion? conclusion)
可以做统一封装

2024-03-29 08:32 UTC, huiyadanli commented on BetterGenshinImpact/Service/Notifier/NotifierManager.cs
> +    }
此处需要 catch 异常，保证后续实现 notifier 的时候即便没有 catch 也无影响，不然出现超时等异常情况时候会直接被最外层的 exception handler 捕获直接出现弹框。多个消息通知同时出错的时候可能会出现大量弹框。

如果要输出log的话，注意bgi对日志的特殊处理：
1. Debug级别的日志只会进入日志文件，不会进入遮罩。推荐用于打印错误堆栈。
2. 其余级别的日志会在遮罩日志框中展示。

2024-03-29 15:50 UTC, emako approved these changes

2024-03-29 15:50 UTC, emako commented on BetterGenshinImpact/ViewModel/Pages/NotificationSettingsPageViewModel.cs
> +    [ObservableProperty] private string _webhookStatus = "";
string.Empty强迫症

2024-03-29 15:50 UTC, emako commented on BetterGenshinImpact/Service/Notification/Converter/ImageToBase64Converter.cs
> +        var stream = new MemoryStream();
using var stream = new MemoryStream();

2024-03-29 18:15 UTC, Mr-Quin commented on BetterGenshinImpact/Service/Notifier/NotifierManager.cs
> +    }
我是想catch应该caller负责，这样可以向上传递错误信息。但是再一想实际使用中应该不需要，需要错误信息的话可以直接获取INotifier。
log目前只输出Debug，但是感觉还是需要某种提示来提醒用户通知出现问题。考虑到SendNotificationAsync可能会高频调用，输出到遮罩窗口有刷屏的可能，不清楚怎么处理好，可能可以throttle？

2024-03-29 18:15 UTC, Mr-Quin commented on BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
> +    private void Notify(NotificationAction action, NotificationConclusion? conclusion)
这个没太懂什么意思，请细说

2024-03-30 02:14 UTC, huiyadanli commented on BetterGenshinImpact/Service/Notifier/NotifierManager.cs
> +    }
输出简短的消息，即便刷屏问题应该也不大 :joy:，至少可以让用户知道这块出问题了。

2024-03-30 02:16 UTC, huiyadanli commented on BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
> +    private void Notify(NotificationAction action, NotificationConclusion? conclusion)
```
private void Notify(NotificationAction action, NotificationConclusion? conclusion)
{
    NotificationManager.Instance().NotifyObservers(new TaskNotificationData
    {
        Event = NotificationEvent.Domain,
        Action = action,
        Conclusion = conclusion,
        Task = _taskParam
    });
}
```

这块能否直接包装到其他静态方法调用内，不放在`Task`内。（小强迫症，放原地也没啥问题）

2024-03-30 02:43 UTC, Mr-Quin commented on BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
> +    private void Notify(NotificationAction action, NotificationConclusion? conclusion)
懂了

2024-03-30 07:51 UTC, Mr-Quin commented on BetterGenshinImpact/Service/Notifier/NotifierManager.cs
> +    }
确实，知道总比不知道好

2024-03-31 02:51 UTC, huiyadanli approved these changes

2024-04-01 03:04 UTC, qhy040404 approved these changes
just code style

2024-04-01 03:04 UTC, qhy040404 commented on BetterGenshinImpact/Service/Notification/Model/NotificationTestResult.cs
> +    public string Message { get; set; } = "";
```suggestion
    public string Message { get; set; } = default!;
```

或者`string.Empty`

2024-04-01 03:04 UTC, qhy040404 commented on BetterGenshinImpact/Service/Notification/NotificationConfig.cs
> +    private string _webhookEndpoint = "";
```suggestion
    private string _webhookEndpoint = string.Empty;
```

2024-04-01 03:04 UTC, qhy040404 commented on BetterGenshinImpact/Service/Notifier/Exception/NotifierException.cs
> +}
```suggestion
public class NotifierException(string message) : System.Exception(message);
```

2024-04-01 06:47 UTC, Lightczx approved these changes

2024-04-01 06:47 UTC, Lightczx commented on BetterGenshinImpact/App.xaml.cs
> +                services.AddHostedService<NotificationService>(sp => sp.GetRequiredService<NotificationService>());
`services.AddHostedService<NotificationService>();`
应该就够了

2024-04-01 07:01 UTC, Mr-Quin commented on BetterGenshinImpact/App.xaml.cs
> +                services.AddHostedService<NotificationService>(sp => sp.GetRequiredService<NotificationService>());
一开始我试了，但是好像DI会出问题，去到通知设置页会报错，后来搜了搜把AddSingleton加回来了
回头我再试试

2024-04-02 01:10 UTC, Lightczx commented on BetterGenshinImpact/App.xaml.cs
> +                services.AddHostedService<NotificationService>(sp => sp.GetRequiredService<NotificationService>());
AddHostedService默认Singleton

2024-04-02 02:39 UTC, Mr-Quin commented on BetterGenshinImpact/App.xaml.cs
> +                services.AddHostedService<NotificationService>(sp => sp.GetRequiredService<NotificationService>());
只有`services.AddHostedService<NotificationService>();`的情况
通知页面报错:
![image](https://github.com/babalae/better-genshin-impact/assets/8700123/4f40173d-01bc-4951-af13-0e415a5eda9d)
是不是还少什么

2024-04-02 02:50 UTC, Lightczx commented on BetterGenshinImpact/App.xaml.cs
> +                services.AddHostedService<NotificationService>(sp => sp.GetRequiredService<NotificationService>());
确实有点问题 AddHostService添加的是IHostSerivce的服务只有使用IEnumerable<IHostService>才能提出来了，那还是保留单独的AddSingleton，再从ServiceProvider里面取吧

2024-04-02 02:51 UTC, Lightczx commented on BetterGenshinImpact/App.xaml.cs
> +                services.AddHostedService<NotificationService>(sp => sp.GetRequiredService<NotificationService>());
https://github.com/dotnet/runtime/blob/0d59506d6c3912d5ee7c659cedaf92846aaefe78/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/ServiceCollectionHostedServiceExtensions.cs#L22

2024-04-04 04:47 UTC, huiyadanli commented
![image](https://github.com/babalae/better-genshin-impact/assets/15783049/0edafdd7-2131-4d11-a1f4-ad0eeaaf0b82)

简单测试了下没有问题，是否可以合并？

2024-04-04 05:02 UTC, huiyadanli commented
还有个问题，默认的Webhook实现是通知到哪的 :joy:

2024-04-04 05:18 UTC, Mr-Quin commented
> 还有个问题，默认的Webhook实现是通知到哪的 😂

并没有特别的地方，我个人的使用场景是discord和homeassistant，写了个脚本转发

2024-04-04 05:18 UTC, merged

2024-12-23 07:26 UTC, Because66666 commented
大佬还在吗，请问这个通知模块有相关的文档吗？我搭建了一个简易本地测试服务器，结果发现在‘全自动’模块中它似乎不起作用。我想知道如何触发这个通知？