Support using both key-mouse-record and auto-pathing in js scripts
babalae/better-genshin-impact pull request #711
Opened 2024-10-17 08:17 UTC by jbcaaa

2024-10-17 14:29 UTC, jbcaaa reviewed
Hello?

2024-10-17 14:38 UTC, huiyadanli commented on BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
> +            }
这段去掉，或者整个冲刺要判断时间间隔，而不是在每段路线的前进中判断。路线足够长的情况下还是会出现体力不足的情况。

2024-10-17 14:38 UTC, huiyadanli commented on BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
> +        }
这段可以的，但是我觉的整套动作随机性仍有提升空间

2024-10-17 16:25 UTC, jbcaaa commented on BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
> +        }
又改了一下，加上了随机旋转视角辅助脱困和冲刺计时器

2024-10-17 16:29 UTC, huiyadanli requested changes

2024-10-17 16:29 UTC, huiyadanli commented on BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
> +            }
这里是正常行走，为什么要加随机值，加了就没法走到正常位置了

2024-10-17 16:52 UTC, jbcaaa commented on BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
> +            }
这回应该能将随机值正常归零了

2024-10-18 07:00 UTC, huiyadanli commented on BetterGenshinImpact/GameTask/AutoPathing/TrapEscaper.cs
> +    }
删除这个方法，直接使用 `TaskControl.Delay` 即可

用法：
```
await Delay(100, cts);
```

2024-10-18 07:00 UTC, huiyadanli commented on BetterGenshinImpact/GameTask/AutoPathing/TrapEscaper.cs
> +        Task.Delay(500).Wait();
Task.Delay(500).Wait(); 写法都换成  `TaskControl.Sleep()`

2024-10-18 12:14 UTC, merged