添加PickAround实现（浅测试）
babalae/better-genshin-impact pull request #721
Opened 2024-10-18 13:36 UTC by jbcaaa

已经经过轻微测试，可以实现基本的转圈采集功能。

2024-10-18 14:14 UTC, huiyadanli requested changes

2024-10-18 14:14 UTC, huiyadanli commented on BetterGenshinImpact/GameTask/AutoPathing/Handler/PickAroundHandler.cs
> +        Simulation.SendInput.Keyboard.KeyDown(User32.VK.VK_W);
KeyDown 以后没有 KeyUp ，会一直前进

2024-10-18 14:19 UTC, huiyadanli commented
1. 按中键回正视角，然后识别当前视角（可能识别错误），以此视角为基准旋转360是否更加符合直觉？或者直接放弃视角，上下左右做正方形运动也能达到类似效果
2. 虽然采集的时候自动开启了自动拾取的触发器，但是速度较慢，使用 PickAround 的场景大概率是圣遗物之类的场景，我觉的循环内加上疯狂的F会更好

2024-10-18 14:30 UTC, Lightczx commented on BetterGenshinImpact/GameTask/AutoPathing/Handler/PickAroundHandler.cs
> +        Simulation.SendInput.Keyboard.KeyDown(User32.VK.VK_W);
@huiyadanli 感觉可以给Simulation.SendInput.Keyboard加个返回IDisposible的方法（比如KeyPress()）
using scope 开头按下 scope 结束弹起

2024-10-19 05:08 UTC, huiyadanli approved these changes

2024-10-19 05:08 UTC, merged